//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.13 at 01:22:57 PM MESZ 
//


package aufgabe4;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the aufgabe4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: aufgabe4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Rezept.Zubereitung.BrennwertAnzeige }
     * 
     */
    public Rezept.Zubereitung.BrennwertAnzeige createRezeptZubereitungBrennwertAnzeige() {
        return new Rezept.Zubereitung.BrennwertAnzeige();
    }

    /**
     * Create an instance of {@link Rezept.Zutaten }
     * 
     */
    public Rezept.Zutaten createRezeptZutaten() {
        return new Rezept.Zutaten();
    }

    /**
     * Create an instance of {@link Rezept.Kommentare.Eintrag }
     * 
     */
    public Rezept.Kommentare.Eintrag createRezeptKommentareEintrag() {
        return new Rezept.Kommentare.Eintrag();
    }

    /**
     * Create an instance of {@link Rezept.Zutaten.Zutat }
     * 
     */
    public Rezept.Zutaten.Zutat createRezeptZutatenZutat() {
        return new Rezept.Zutaten.Zutat();
    }

    /**
     * Create an instance of {@link Rezept.Zubereitung }
     * 
     */
    public Rezept.Zubereitung createRezeptZubereitung() {
        return new Rezept.Zubereitung();
    }

    /**
     * Create an instance of {@link Rezept.Kommentare }
     * 
     */
    public Rezept.Kommentare createRezeptKommentare() {
        return new Rezept.Kommentare();
    }

    /**
     * Create an instance of {@link Rezept }
     * 
     */
    public Rezept createRezept() {
        return new Rezept();
    }

}
