//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.13 at 01:22:57 PM MESZ 
//


package aufgabe4;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="titel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="fotos" type="{http://www.w3.org/2001/XMLSchema}anyURI"/>
 *         &lt;element name="zutaten">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="zutat" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="menge" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *                             &lt;element name="einheit">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;enumeration value="g"/>
 *                                   &lt;enumeration value="kg"/>
 *                                   &lt;enumeration value="Msp."/>
 *                                   &lt;enumeration value="cl"/>
 *                                   &lt;enumeration value="ml"/>
 *                                   &lt;enumeration value="dl"/>
 *                                   &lt;enumeration value="EL"/>
 *                                   &lt;enumeration value="TL"/>
 *                                   &lt;enumeration value="Pkt."/>
 *                                   &lt;enumeration value="Ei"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                           &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="portionen" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="zubereitung">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="arbeitszeit" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="schwierigkeitsgrad">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;enumeration value="simpel"/>
 *                         &lt;enumeration value="mittel"/>
 *                         &lt;enumeration value="schwierig"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="brennwertAnzeige">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="menge2" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
 *                             &lt;element name="brennwert" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="kommentare">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="eintrag" maxOccurs="unbounded" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="autor" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "titel",
    "fotos",
    "zutaten",
    "portionen",
    "zubereitung",
    "kommentare"
})
@XmlRootElement(name = "rezept")
public class Rezept {

    @XmlElement(required = true)
    protected String titel;
    @XmlElement(required = true)
    @XmlSchemaType(name = "anyURI")
    protected String fotos;
    @XmlElement(required = true)
    protected Rezept.Zutaten zutaten;
    @XmlElement(required = true)
    protected BigInteger portionen;
    @XmlElement(required = true)
    protected Rezept.Zubereitung zubereitung;
    @XmlElement(required = true)
    protected Rezept.Kommentare kommentare;

    /**
     * Gets the value of the titel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitel() {
        return titel;
    }

    /**
     * Sets the value of the titel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitel(String value) {
        this.titel = value;
    }

    /**
     * Gets the value of the fotos property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFotos() {
        return fotos;
    }

    /**
     * Sets the value of the fotos property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFotos(String value) {
        this.fotos = value;
    }

    /**
     * Gets the value of the zutaten property.
     * 
     * @return
     *     possible object is
     *     {@link Rezept.Zutaten }
     *     
     */
    public Rezept.Zutaten getZutaten() {
        return zutaten;
    }

    /**
     * Sets the value of the zutaten property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rezept.Zutaten }
     *     
     */
    public void setZutaten(Rezept.Zutaten value) {
        this.zutaten = value;
    }

    /**
     * Gets the value of the portionen property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPortionen() {
        return portionen;
    }

    /**
     * Sets the value of the portionen property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPortionen(BigInteger value) {
        this.portionen = value;
    }

    /**
     * Gets the value of the zubereitung property.
     * 
     * @return
     *     possible object is
     *     {@link Rezept.Zubereitung }
     *     
     */
    public Rezept.Zubereitung getZubereitung() {
        return zubereitung;
    }

    /**
     * Sets the value of the zubereitung property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rezept.Zubereitung }
     *     
     */
    public void setZubereitung(Rezept.Zubereitung value) {
        this.zubereitung = value;
    }

    /**
     * Gets the value of the kommentare property.
     * 
     * @return
     *     possible object is
     *     {@link Rezept.Kommentare }
     *     
     */
    public Rezept.Kommentare getKommentare() {
        return kommentare;
    }

    /**
     * Sets the value of the kommentare property.
     * 
     * @param value
     *     allowed object is
     *     {@link Rezept.Kommentare }
     *     
     */
    public void setKommentare(Rezept.Kommentare value) {
        this.kommentare = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="eintrag" maxOccurs="unbounded" minOccurs="0">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="autor" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "eintrag"
    })
    public static class Kommentare {

        protected List<Rezept.Kommentare.Eintrag> eintrag;

        /**
         * Gets the value of the eintrag property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the eintrag property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEintrag().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rezept.Kommentare.Eintrag }
         * 
         * 
         */
        public List<Rezept.Kommentare.Eintrag> getEintrag() {
            if (eintrag == null) {
                eintrag = new ArrayList<Rezept.Kommentare.Eintrag>();
            }
            return this.eintrag;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="autor" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="datum" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "autor",
            "datum",
            "text"
        })
        public static class Eintrag {

            @XmlElement(required = true)
            protected String autor;
            @XmlElement(required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar datum;
            @XmlElement(required = true)
            protected String text;

            /**
             * Gets the value of the autor property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getAutor() {
                return autor;
            }

            /**
             * Sets the value of the autor property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setAutor(String value) {
                this.autor = value;
            }

            /**
             * Gets the value of the datum property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getDatum() {
                return datum;
            }

            /**
             * Sets the value of the datum property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setDatum(XMLGregorianCalendar value) {
                this.datum = value;
            }

            /**
             * Gets the value of the text property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getText() {
                return text;
            }

            /**
             * Sets the value of the text property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setText(String value) {
                this.text = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="arbeitszeit" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="schwierigkeitsgrad">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;enumeration value="simpel"/>
     *               &lt;enumeration value="mittel"/>
     *               &lt;enumeration value="schwierig"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="brennwertAnzeige">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="menge2" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
     *                   &lt;element name="brennwert" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *         &lt;element name="text" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "arbeitszeit",
        "schwierigkeitsgrad",
        "brennwertAnzeige",
        "text"
    })
    public static class Zubereitung {

        @XmlElement(required = true)
        protected BigInteger arbeitszeit;
        @XmlElement(required = true)
        protected String schwierigkeitsgrad;
        @XmlElement(required = true)
        protected Rezept.Zubereitung.BrennwertAnzeige brennwertAnzeige;
        @XmlElement(required = true)
        protected String text;

        /**
         * Gets the value of the arbeitszeit property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getArbeitszeit() {
            return arbeitszeit;
        }

        /**
         * Sets the value of the arbeitszeit property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setArbeitszeit(BigInteger value) {
            this.arbeitszeit = value;
        }

        /**
         * Gets the value of the schwierigkeitsgrad property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getSchwierigkeitsgrad() {
            return schwierigkeitsgrad;
        }

        /**
         * Sets the value of the schwierigkeitsgrad property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setSchwierigkeitsgrad(String value) {
            this.schwierigkeitsgrad = value;
        }

        /**
         * Gets the value of the brennwertAnzeige property.
         * 
         * @return
         *     possible object is
         *     {@link Rezept.Zubereitung.BrennwertAnzeige }
         *     
         */
        public Rezept.Zubereitung.BrennwertAnzeige getBrennwertAnzeige() {
            return brennwertAnzeige;
        }

        /**
         * Sets the value of the brennwertAnzeige property.
         * 
         * @param value
         *     allowed object is
         *     {@link Rezept.Zubereitung.BrennwertAnzeige }
         *     
         */
        public void setBrennwertAnzeige(Rezept.Zubereitung.BrennwertAnzeige value) {
            this.brennwertAnzeige = value;
        }

        /**
         * Gets the value of the text property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getText() {
            return text;
        }

        /**
         * Sets the value of the text property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setText(String value) {
            this.text = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="menge2" type="{http://www.w3.org/2001/XMLSchema}positiveInteger"/>
         *         &lt;element name="brennwert" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "menge2",
            "brennwert"
        })
        public static class BrennwertAnzeige {

            @XmlElement(required = true)
            @XmlSchemaType(name = "positiveInteger")
            protected BigInteger menge2;
            @XmlElement(required = true)
            protected String brennwert;

            /**
             * Gets the value of the menge2 property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getMenge2() {
                return menge2;
            }

            /**
             * Sets the value of the menge2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setMenge2(BigInteger value) {
                this.menge2 = value;
            }

            /**
             * Gets the value of the brennwert property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBrennwert() {
                return brennwert;
            }

            /**
             * Sets the value of the brennwert property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBrennwert(String value) {
                this.brennwert = value;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="zutat" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="menge" type="{http://www.w3.org/2001/XMLSchema}float"/>
     *                   &lt;element name="einheit">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;enumeration value="g"/>
     *                         &lt;enumeration value="kg"/>
     *                         &lt;enumeration value="Msp."/>
     *                         &lt;enumeration value="cl"/>
     *                         &lt;enumeration value="ml"/>
     *                         &lt;enumeration value="dl"/>
     *                         &lt;enumeration value="EL"/>
     *                         &lt;enumeration value="TL"/>
     *                         &lt;enumeration value="Pkt."/>
     *                         &lt;enumeration value="Ei"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *                 &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "zutat"
    })
    public static class Zutaten {

        @XmlElement(required = true)
        protected List<Rezept.Zutaten.Zutat> zutat;

        /**
         * Gets the value of the zutat property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the zutat property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getZutat().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link Rezept.Zutaten.Zutat }
         * 
         * 
         */
        public List<Rezept.Zutaten.Zutat> getZutat() {
            if (zutat == null) {
                zutat = new ArrayList<Rezept.Zutaten.Zutat>();
            }
            return this.zutat;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="bezeichnung" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="menge" type="{http://www.w3.org/2001/XMLSchema}float"/>
         *         &lt;element name="einheit">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;enumeration value="g"/>
         *               &lt;enumeration value="kg"/>
         *               &lt;enumeration value="Msp."/>
         *               &lt;enumeration value="cl"/>
         *               &lt;enumeration value="ml"/>
         *               &lt;enumeration value="dl"/>
         *               &lt;enumeration value="EL"/>
         *               &lt;enumeration value="TL"/>
         *               &lt;enumeration value="Pkt."/>
         *               &lt;enumeration value="Ei"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *       &lt;/sequence>
         *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}short" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bezeichnung",
            "menge",
            "einheit"
        })
        public static class Zutat {

            @XmlElement(required = true)
            protected String bezeichnung;
            protected float menge;
            @XmlElement(required = true)
            protected String einheit;
            @XmlAttribute
            protected Short id;

            /**
             * Gets the value of the bezeichnung property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getBezeichnung() {
                return bezeichnung;
            }

            /**
             * Sets the value of the bezeichnung property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setBezeichnung(String value) {
                this.bezeichnung = value;
            }

            /**
             * Gets the value of the menge property.
             * 
             */
            public float getMenge() {
                return menge;
            }

            /**
             * Sets the value of the menge property.
             * 
             */
            public void setMenge(float value) {
                this.menge = value;
            }

            /**
             * Gets the value of the einheit property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEinheit() {
                return einheit;
            }

            /**
             * Sets the value of the einheit property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEinheit(String value) {
                this.einheit = value;
            }

            /**
             * Gets the value of the id property.
             * 
             * @return
             *     possible object is
             *     {@link Short }
             *     
             */
            public Short getId() {
                return id;
            }

            /**
             * Sets the value of the id property.
             * 
             * @param value
             *     allowed object is
             *     {@link Short }
             *     
             */
            public void setId(Short value) {
                this.id = value;
            }

        }

    }

}
